execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
set(expected "0 255\ntrue false\n")
if(NOT result EQUAL 0 OR NOT output STREQUAL expected)
    message(FATAL_ERROR "affichage Byte/Bool invalide: code=${result}, sortie=[${output}]")
endif()
