file(READ "${IR_FILE}" ir)
string(REGEX MATCHALL "function generic_monomorphization__identity__Int__g[0-9a-f]+" int_instances "${ir}")
list(LENGTH int_instances count)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "identity[Int] doit produire une seule instance, reçu ${count}")
endif()
foreach(name IN ITEMS Byte String Box_Int_)
    if(NOT ir MATCHES "function generic_monomorphization__identity__${name}__g[0-9a-f]+")
        message(FATAL_ERROR "instance identity__${name} canonique manquante")
    endif()
endforeach()
