#!/usr/bin/env bash
set -euo pipefail
compiler="$1"
source="$2"
output="$3"
rm -f "${output}" "${output}.ll" "${output}.ir" "${output}.asm" "${output}.fasm" "${output}.fasm.ir" "${output}.fasm.asm" "${output}.clang.out" "${output}.fasm.out" "${output}.expected"
"${compiler}" "${source}" --backend=clang -o "${output}"
test -x "${output}"
test -f "${output}.ll"
test -f "${output}.ir"
test ! -f "${output}.asm"
grep -Fq 'declare i64 @write(i32, ptr, i64)' "${output}.ll"
grep -Fq 'lshr i32' "${output}.ll"
grep -Fq 'trunc i32' "${output}.ll"
"${output}" > "${output}.clang.out"
printf 'Aé🚀\n' > "${output}.expected"
cmp -s "${output}.expected" "${output}.clang.out"
"${compiler}" "${source}" --backend=fasm -o "${output}.fasm"
"${output}.fasm" > "${output}.fasm.out"
cmp -s "${output}.fasm.out" "${output}.clang.out"
