file(READ "${IR_FILE}" ir)
string(REGEX MATCHALL "function identity__Int" int_instances "${ir}")
list(LENGTH int_instances count)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "identity[Int] doit produire une seule instance, reçu ${count}")
endif()
foreach(name IN ITEMS Byte String Box_Int_)
    if(NOT ir MATCHES "function identity__${name}")
        message(FATAL_ERROR "instance identity__${name} manquante")
    endif()
endforeach()
