execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
set(expected "0 -2147483648 42\n")
if(NOT result EQUAL 0 OR NOT output STREQUAL expected)
    message(FATAL_ERROR "affichage Int invalide: code=${result}, sortie=[${output}]")
endif()
