#!/usr/bin/env bash
set -euo pipefail
compiler="$1"
source="$2"
output="$3"
rm -f "${output}" "${output}.ll" "${output}.ir" "${output}.asm" "${output}.fasm" "${output}.fasm.ir" "${output}.fasm.asm" "${output}.stdout" "${output}.fasm.stdout" "${output}.expected"
"${compiler}" "${source}" --backend=clang -o "${output}"
test -x "${output}"
test -f "${output}.ll"
test -f "${output}.ir"
test ! -e "${output}.asm"
grep -Fq "declare i64 @write(i32, ptr, i64)" "${output}.ll"
grep -Fq "@zeta.bool.true" "${output}.ll"
grep -Fq "@zeta.bool.false" "${output}.ll"
grep -Fq "call i64 @write(i32 1" "${output}.ll"
"${output}" > "${output}.stdout"
printf 'truefalse\n' > "${output}.expected"
cmp "${output}.expected" "${output}.stdout"
"${compiler}" "${source}" -o "${output}.fasm"
"${output}.fasm" > "${output}.fasm.stdout"
cmp "${output}.fasm.stdout" "${output}.stdout"
